version: '3.8'

services:
  mailer:
    image: php:${PHP_VERSION}-apache
    container_name: mailer
    restart: unless-stopped
    ports:
      - 85:80
    environment:
      - ENV=${ENV}
      - TEST_ADDRESS=${TEST_ADDRESS}
      - TEST_ADDRESS_NAME=${TEST_ADDRESS_NAME}
      - MAIL_SMTP_SERVER=${MAIL_SMTP_SERVER}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - MAIL_SMTP_USER=${MAIL_SMTP_USER}
      - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - POSTMARK_API_KEY=${POSTMARK_API_KEY}
      - MAILERSEND_API_KEY=${MAILERSEND_API_KEY}
    volumes:
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
      - .:/var/www
